# Generated by Django 4.0.4 on 2022-05-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0002_alter_archivo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='file',
            field=models.FileField(upload_to='archivos'),
        ),
    ]
