# Generated by Django 4.0.4 on 2022-05-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0003_alter_archivo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
