# Generated by Django 4.0.4 on 2022-05-17 01:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0004_alter_archivo_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='archivos',
        ),
        migrations.AddField(
            model_name='post',
            name='archivos',
            field=models.ForeignKey(default=datetime.date, on_delete=django.db.models.deletion.CASCADE, to='Archivo.archivo'),
            preserve_default=False,
        ),
    ]
