# Generated by Django 4.0.4 on 2022-05-02 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_remove_document_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
