# Generated by Django 4.0.4 on 2022-05-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_remove_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
