# Generated by Django 4.0.4 on 2022-05-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
