# Generated by Django 4.0.4 on 2022-05-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='titulo',
            field=models.CharField(max_length=80),
        ),
    ]
