# Generated by Django 4.0.4 on 2022-05-24 21:00

import carga.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0002_alter_documents_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diccionario',
            name='newDiccionario',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documents',
            name='documento',
            field=models.FileField(upload_to='documents', validators=[carga.validators.validate_file_extension]),
        ),
    ]
