# Generated by Django 4.0.4 on 2022-05-24 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0003_diccionario_newdiccionario_alter_documents_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diccionario',
            name='newDiccionario',
        ),
    ]
