# Generated by Django 4.0.4 on 2022-05-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0004_remove_diccionario_newdiccionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='diccionario',
            name='newDiccionario',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
