# Generated by Django 4.0.4 on 2022-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carga', '0008_imagen_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
